# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       sdk-client

# >> macros
# << macros

Summary:    Mer SDK client tools
Version:    0.5
Release:    1
Group:      Development Platform/Platform SDK
License:    GPLv2+
BuildArch:  noarch
URL:        https://github.com/mer-tools/sdk-setup
Source0:    sdk-client-%{version}.tar.gz
Source100:  sdk-client.yaml
Requires:   sudo
Requires:   openssh-server
Requires:   rsync
BuildRequires:  systemd

%description
Tools to support the Mer Qt Creator

%package emul
Summary:    Mer SDK files for the Emulator VM
Group:      System/Base
Requires:   %{name} = %{version}-%{release}
Requires:   connman >= 1.14
Requires:   virtualbox-guest-tools
Requires(post): /bin/ln
Conflicts:  sdk-vm

%description emul
Contains the supporting configs for Emulator VMs to setup shared folders and the internal LAN for the SDK build engine

%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
%post emul
%systemd_post etc-mersdk-share.mount
%systemd_post etc-ssh-authorized_keys.mount
%systemd_post sdk-emulan.service
# << install post

%preun
# >> preun
%preun emul
%systemd_preun etc-mersdk-share.mount
%systemd_preun etc-ssh-authorized_keys.mount
%systemd_preun sdk-emulan.service
# << preun

%postun
# >> postun
%postun emul
%systemd_postun
# << postun

%files
%defattr(-,root,root,-)
%{_bindir}/install-rpm
# >> files
# << files

%files emul
%defattr(-,root,root,-)
%{_sysconfdir}/*
%{_bindir}/sdk-shutdown
%{_bindir}/sdk-setup-emulan
%{_unitdir}/sdk-emulan.service
%{_unitdir}/etc-mersdk-share.mount
%{_unitdir}/etc-ssh-authorized_keys.mount
# >> files emul
# << files emul
