#!/bin/bash
#
# Copyright (C) 2012 David Greaves <david.greaves@jollamobile.com>
# License GPL2+
#
# This script is used by QtCreator to install packages produced by the
# Mer SDK.
#

ME=$0

usage() {
    cat <<EOF
   $ME <pkg>

   Installs (or upgrades) a package.

   sudo must be enabled in passwd-less mode for the zypper command.
EOF

}
assert_sudo_enabled() {
    if sudo -n /usr/bin/zypper --version >/dev/null 2>&1; then
	return
    else
	echo "sudo did not work without a passwd for /usr/bin/zypper"
	echo "$ME cannot run"
	exit 1
    fi
}

install_package() {
    sudo -n /usr/bin/zypper --non-interactive in $1
}

assert_sudo_enabled

pkg=$1

if [[ ! $pkg ]]; then
    usage
    exit 1
fi

install_package $pkg
